/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myattempt;

import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.swing.Box;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author KOUSHIKI
 */
class Student{
    int id;
    String name;
    int age;
    String gender;
    public Student(String name, int age, String gender)
    {
        this.name=name;
        this.age=age;
        this.gender=gender;
    }
    public Student(int idd,String name, int age, String gender)
    {
        this.id=idd;
        this.name=name;
        this.age=age;
        this.gender=gender;
    }
}

public class myattempt extends javax.swing.JFrame{

    /**
     * Creates new form myattempt
     */
    
    static int removeflag=1;
    static int addflag=0;
    static int flag=0;
    static int emptycomboflag=1;
    static ArrayList<Student>a = new ArrayList(0);
    static ArrayList<JLabel>opslabel=new ArrayList(0);
    static ArrayList<JCheckBox>opscheck=new ArrayList(0);

 
    public void update(String data)
    {
        jLabel5.setText(data);
    }
    public myattempt() {
        initComponents();
        jComboBox1.setVisible(true);
         Socket socket;
        DataOutputStream dout;
        Scanner sc;
        ObjectOutputStream outdata;
        try {
            socket= new Socket("172.26.162.38",5000);
            //System.out.println("COnnected");
            new ReadThread1(socket,this);
            
        }catch(IOException ee)
        {
        }
        for(Student ss:a){
            jComboBox1.addItem(ss.id+" "+ss.name);
        }
    }
    public void addToComboBox(String n)
    {
        jComboBox1.addItem(n);
        emptycomboflag=0;
    }
public void openthis(){
    this.setVisible(true);
            
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        //jComboBox1.setVisible(false);
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\KOUSHIKI\\Desktop\\java programs\\AWP proj\\src\\myattempt\\newusericon.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jLabel3.setText("Welcome ");
        jLabel3.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("You can add, modify and remove details from our database! Thank you for your support.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(332, 332, 332))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButton1)
                .addGap(136, 136, 136)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        jMenu1.setText("PERSON");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("SIGNUP");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("LOGIN");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("MODIFY");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int y=0;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        //addflag=1;
        JTextField name = new JTextField();
        JTextField age = new JTextField();
        ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        JRadioButton b1 = new javax.swing.JRadioButton();
        JRadioButton b2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(b1);
        b1.setText("Male");
         buttonGroup1.add(b2);
        b2.setText("Female");
        name.setColumns(10);
        age.setColumns(10);
        JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("Name:"));
      myPanel.add(name);
      myPanel.add(Box.createHorizontalStrut(15)); // a spacer
      myPanel.add(new JLabel("Age:"));
      myPanel.add(age);
      myPanel.add(new JLabel("Gender:"));
      myPanel.add(b1);
      myPanel.add(b2);
      int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Please Enter Name,Age and gender Values", JOptionPane.OK_CANCEL_OPTION);
      if(result == JOptionPane.OK_OPTION){
          String gender;
      if(b1.isSelected())
      {
          gender=b1.getText();
      }
      else
      {
          gender=b2.getText();
      }
      int ageint = Integer.parseInt(age.getText());
     
        Student s = new Student(name.getText(),ageint,gender);
        a.add(s);
        jComboBox1.setVisible(true);
        jComboBox1.addItem(name.getText());
         if(emptycomboflag==1)
          {
              jComboBox1.setVisible(true);
              emptycomboflag=0;
          }
      }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //System.out.println(flag);
       // TODO add your handling code here:
        //System.out.println(flag);
       if(emptycomboflag==0&& y==0){
           
        Object selected = jComboBox1.getSelectedItem();
        
        String name=selected.toString();
        JLabel ol=new JLabel();
        ol.setText(name);
        opslabel.add(ol);
        JCheckBox oj =new JCheckBox();
        opscheck.add(oj);
        jPanel3.setLayout(new FlowLayout());
        jPanel3.add(ol);
        jPanel3.add(oj);
        jPanel3.revalidate();
        jPanel3.repaint();
        addflag=0;
      }
       /*else 
       {
           if(emptycomboflag==1){
           jComboBox1.setVisible(false);
           }
           if(y==1)
           {
               y=0;
           }
       }*/
       
       
        
        //jPanel2.setLayout(new FlowLayout());
        //ops.add(o);
  
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JTextField id= new JTextField();
        JPasswordField pwd = new JPasswordField();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id.setColumns(10);
        pwd.setColumns(10);
        JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("Enter ID:"));
      myPanel.add(id);
      myPanel.add(Box.createHorizontalStrut(15)); // a spacer
      myPanel.add(new JLabel("Enter Password:"));
      myPanel.add(pwd);
      int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "LOGIN WINDOW", JOptionPane.OK_CANCEL_OPTION);
      if(result == JOptionPane.OK_OPTION){
      String userid=id.getText();
      String pswd =pwd.toString();
      
      Socket socket;
		DataOutputStream dout;
		Scanner sc;
		ObjectOutputStream outdata;
        try {
            socket= new Socket("10.18.2.178",5000);
			System.out.println("COnnected");
			dout= new DataOutputStream(socket.getOutputStream());
			 sc =new Scanner(System.in);
			 String line=userid+":"+pswd;
			 new ReadThread(socket);
                         try{
                        dout.writeUTF(line);
			}catch(Exception e){
				System.out.println("Caughtw");
				try{
					dout.close();
				}catch(Exception ex){
					System.out.println("Caughte");
				}
			}
                        try{
                            dout.close();
			}catch(IOException e){
				System.out.println("Caughtr");
			}
                        
        } catch (IOException ex) {
            Logger.getLogger(myattempt.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_jMenuItem3ActionPerformed
public void closethis(){
    this.setVisible(false);
}
    class ReadThread extends Thread{
    Socket socket;
    DataInputStream din;
    ReadThread(Socket s){
        socket=s;
        try {
            din= new DataInputStream(socket.getInputStream());
        } catch (IOException ex) {
            System.out.println("Caught4");
        }
		start();
    }
    @Override
    public void run(){
        String flag;
        try{
            flag=din.readUTF();
            if(flag.equals("1"))
            {
                closethis();
                //create new window
            }
            else
            {
                //error msg
            }
        }catch(Exception eee){
            
        }
        
    }
}
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int i=-1,flag=0,f=0,k,m,j=0;
        String nm;
        int ag;
        y=1;
        //Object o=evt.getSource();
        for(k=0;((k<opscheck.size())&&(f==0));k++)
        {
            if(opscheck.get(k).isSelected())
            {
                f=1;
                i=k;
            }
            
        }
        String name=opslabel.get(i).getText();
        for(m=0;((m<a.size())&&(flag==0));m++)
        {
            if(a.get(m).name.equals(name))
            {
                flag=1;
                j = m;
            }
        }
        JTextField name1 = new JTextField();
        JTextField age = new JTextField();
         ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        JRadioButton b1 = new javax.swing.JRadioButton();
        JRadioButton b2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(b1);
        b1.setText("Male");
         buttonGroup1.add(b2);
        b2.setText("Female");
        name1.setColumns(10);
        age.setColumns(10);
        JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("Name:"));
      myPanel.add(name1);
      myPanel.add(Box.createHorizontalStrut(15)); // a spacer
      myPanel.add(new JLabel("Age:"));
      myPanel.add(age);
      myPanel.add(new JLabel("Gender:"));
      myPanel.add(b1);
      myPanel.add(b2);
      int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Please Enter Name,Age and gender Values", JOptionPane.OK_CANCEL_OPTION);
      if(result == JOptionPane.OK_OPTION){
                nm=name1.getText();
                ag=Integer.parseInt(age.getText());
                a.get(j).name=nm;
                a.get(j).age=ag;
                String gender;
                if(b1.isSelected())
                {
                    gender=b1.getText();
                }
                else
                {
                    gender=b2.getText();
                }
                a.get(j).gender=gender;
                jComboBox1.insertItemAt(nm, j);
                jComboBox1.removeItem(opslabel.get(i).getText());
                
                opslabel.get(i).setText(nm);
        }                                          
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new mainframe(this).setVisible(true);
        
        closethis();
        
    }//GEN-LAST:event_jButton1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myattempt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myattempt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myattempt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myattempt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
       
        //combo.setVisible(false);
        /* Create and display the form*/ 
        java.awt.EventQueue.invokeLater(() -> {
            myattempt h=new myattempt();
            h.setVisible(true);
        
        });
        
        
        
    
            
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    
        
    

    
}
